### ISSUE TITLE
save-exact is an antipattern

### ISSUE THREAD

**Issue by jasonkarns** [ericdouglas/blog-assets#2]
There are lots of differing opinions on saving versions, but I'm going to take a small leap and assume that the author falls into the semver++ crowd? (based on the suggestion to `Use Semantic Versioning to bump the version correctly` and recommendation to use `semantic-release`)

saving exact versions is antithetical to semver because it prevents your app/lib from receiving bug fixes. If stability is required, shrinkwraps should be used.

**Comment by ericdouglas** [comment]
@jasonkarns 

what you said makes sense, as well as saving exact versions in order to prevent a broken build/product, IMO.

There are pros and cons in both approaches.

In that article, specifically, my intention was to strictly summarize the course's content.

Anyway, thank you very much for pointing out those things. :smile:

**Comment by jasonkarns** [comment]
> as well as saving exact versions in order to prevent a broken build/product, IMO.

agreed, though that is the role of npm-shrinkwrap, no? saving exact version neuters semver, and isn't necessary if you're using a shrinkwrap.
